Script started on Mon Jun 29 00:05:25 2015
[?1034h]0;fxfitz@ares: ~/multiprocess-wordcounter[01;32mfxfitz@ares[00m:[01;34m~/multiprocess-wordcounter[00m$ ./main.py -f books/* --pad[K[K[Kipaddr  0.0.0.0 --port 5555 -n 0


waiting for a working to connect...



the 21399
of 12617
and 11869
to 10086
a 9269
in 7354
he 5676
i 5605
his 4685
it 4683
]0;fxfitz@ares: ~/multiprocess-wordcounter[01;32mfxfitz@ares[00m:[01;34m~/multiprocess-wordcounter[00m$ 
]0;fxfitz@ares: ~/multiprocess-wordcounter[01;32mfxfitz@ares[00m:[01;34m~/multiprocess-wordcounter[00m$ 
]0;fxfitz@ares: ~/multiprocess-wordcounter[01;32mfxfitz@ares[00m:[01;34m~/multiprocess-wordcounter[00m$ waiting for a working to conne ct...
bash: waiting: command not found
]0;fxfitz@ares: ~/multiprocess-wordcounter[01;32mfxfitz@ares[00m:[01;34m~/multiprocess-wordcounter[00m$ 
]0;fxfitz@ares: ~/multiprocess-wordcounter[01;32mfxfitz@ares[00m:[01;34m~/multiprocess-wordcounter[00m$ 
]0;fxfitz@ares: ~/multiprocess-wordcounter[01;32mfxfitz@ares[00m:[01;34m~/multiprocess-wordcounter[00m$ 
]0;fxfitz@ares: ~/multiprocess-wordcounter[01;32mfxfitz@ares[00m:[01;34m~/multiprocess-wordcounter[00m$ echo WORKED
WORKED
]0;fxfitz@ares: ~/multiprocess-wordcounter[01;32mfxfitz@ares[00m:[01;34m~/multiprocess-wordcounter[00m$ exit
exit

Script done on Mon Jun 29 00:06:22 2015
