Script started on Sun Jun 28 23:54:25 2015
[?1034h]0;fxfitz@ares: ~/multiprocess-wordcounter[01;32mfxfitz@ares[00m:[01;34m~/multiprocess-wordcounter[00m$ ls
INSTALL     LIMITATIONS [1m[36mbooks[39;49m[0m       [1m[31mmain.py[39;49m[0m
LICENSE     README      [1m[36mlib[39;49m[0m         [1m[36msamples[39;49m[0m
]0;fxfitz@ares: ~/multiprocess-wordcounter[01;32mfxfitz@ares[00m:[01;34m~/multiprocess-wordcounter[00m$ python main.py -f books/aliceinnwonderland.txt 
the 1818
and 940
to 809
a 690
of 631
it 610
she 553
i 543
you 481
said 462
]0;fxfitz@ares: ~/multiprocess-wordcounter[01;32mfxfitz@ares[00m:[01;34m~/multiprocess-wordcounter[00m$ exit
exit

Script done on Sun Jun 28 23:54:40 2015
