Script started on Sun Jun 28 23:56:22 2015
[?1034h]0;fxfitz@ares: ~/multiprocess-wordcounter[01;32mfxfitz@ares[00m:[01;34m~/multiprocess-wordcounter[00m$ ./main.py -f *[Kbooks/* -d
DEBUG:root:Multiprocessing Server Started: 127.0.0.1:31337
DEBUG:root:Total jobs in job queue: 3
DEBUG:root:Client connected to 127.0.0.1:31337
DEBUG:root:Created process 0
DEBUG:root:Created process 1
DEBUG:root:Created process 2
DEBUG:root:Created process 3
DEBUG:root:Created process 4
DEBUG:root:Created process 5
DEBUG:root:Created process 6
DEBUG:root:Created process 7
DEBUG:root:<Process(Process-2, started)>: STARTING UP!
DEBUG:root:<Process(Process-3, started)>: STARTING UP!
DEBUG:root:<Process(Process-4, started)>: STARTING UP!
DEBUG:root:<Process(Process-5, started)>: STARTING UP!
DEBUG:root:<Process(Process-7, started)>: STARTING UP!
DEBUG:root:<Process(Process-2, started)>: I have a job!!!
DEBUG:root:<Process(Process-6, started)>: STARTING UP!
DEBUG:root:<Process(Process-8, started)>: STARTING UP!
DEBUG:root:<Process(Process-3, started)>: I have a job!!!
DEBUG:root:<Process(Process-9, started)>: STARTING UP!
DEBUG:root:<Process(Process-5, started)>: No work! Returning.
DEBUG:root:<Process(Process-6, started)>: No work! Returning.
DEBUG:root:<Process(Process-7, started)>: No work! Returning.
DEBUG:root:<Process(Process-4, started)>: I have a job!!!
DEBUG:root:<Process(Process-9, started)>: No work! Returning.
DEBUG:root:<Process(Process-8, started)>: No work! Returning.
DEBUG:root:<Process(Process-2, started)>: Added results to the result_queue
DEBUG:root:<Process(Process-2, started)>: No work! Returning.
DEBUG:root:<Process(Process-3, started)>: Added results to the result_queue
DEBUG:root:<Process(Process-3, started)>: No work! Returning.
DEBUG:root:<Process(Process-4, started)>: Added results to the result_queue
DEBUG:root:<Process(Process-4, started)>: No work! Returning.
DEBUG:root:Items in job queue: 0
DEBUG:root:Items in result queue: 3
DEBUG:root:Beginning to combine the results queue
DEBUG:root:I have combined the results queue!
the 21399
of 12617
and 11869
to 10086
a 9269
in 7354
he 5676
i 5605
his 4685
it 4683
]0;fxfitz@ares: ~/multiprocess-wordcounter[01;32mfxfitz@ares[00m:[01;34m~/multiprocess-wordcounter[00m$ ./main.py -f books/* -d -n 1
DEBUG:root:Multiprocessing Server Started: 127.0.0.1:31337
DEBUG:root:Total jobs in job queue: 3
DEBUG:root:Client connected to 127.0.0.1:31337
DEBUG:root:Created process 0
DEBUG:root:<Process(Process-2, started)>: STARTING UP!
DEBUG:root:<Process(Process-2, started)>: I have a job!!!
DEBUG:root:<Process(Process-2, started)>: Added results to the result_queue
DEBUG:root:<Process(Process-2, started)>: I have a job!!!
DEBUG:root:<Process(Process-2, started)>: Added results to the result_queue
DEBUG:root:<Process(Process-2, started)>: I have a job!!!
DEBUG:root:<Process(Process-2, started)>: Added results to the result_queue
DEBUG:root:<Process(Process-2, started)>: No work! Returning.
DEBUG:root:Items in job queue: 0
DEBUG:root:Items in result queue: 3
DEBUG:root:Beginning to combine the results queue
DEBUG:root:I have combined the results queue!
the 21399
of 12617
and 11869
to 10086
a 9269
in 7354
he 5676
i 5605
his 4685
it 4683
]0;fxfitz@ares: ~/multiprocess-wordcounter[01;32mfxfitz@ares[00m:[01;34m~/multiprocess-wordcounter[00m$ ./main.py -f books/* -d -n 1[K3
DEBUG:root:Multiprocessing Server Started: 127.0.0.1:31337
DEBUG:root:Total jobs in job queue: 3
DEBUG:root:Client connected to 127.0.0.1:31337
DEBUG:root:Created process 0
DEBUG:root:Created process 1
DEBUG:root:Created process 2
DEBUG:root:<Process(Process-2, started)>: STARTING UP!
DEBUG:root:<Process(Process-3, started)>: STARTING UP!
DEBUG:root:<Process(Process-4, started)>: STARTING UP!
DEBUG:root:<Process(Process-3, started)>: I have a job!!!
DEBUG:root:<Process(Process-2, started)>: I have a job!!!
DEBUG:root:<Process(Process-4, started)>: I have a job!!!
DEBUG:root:<Process(Process-3, started)>: Added results to the result_queue
DEBUG:root:<Process(Process-3, started)>: No work! Returning.
DEBUG:root:<Process(Process-2, started)>: Added results to the result_queue
DEBUG:root:<Process(Process-2, started)>: No work! Returning.
DEBUG:root:<Process(Process-4, started)>: Added results to the result_queue
DEBUG:root:<Process(Process-4, started)>: No work! Returning.
DEBUG:root:Items in job queue: 0
DEBUG:root:Items in result queue: 3
DEBUG:root:Beginning to combine the results queue
DEBUG:root:I have combined the results queue!
the 21399
of 12617
and 11869
to 10086
a 9269
in 7354
he 5676
i 5605
his 4685
it 4683
]0;fxfitz@ares: ~/multiprocess-wordcounter[01;32mfxfitz@ares[00m:[01;34m~/multiprocess-wordcounter[00m$ ./main.py -f books/* -d -n 3[K20
DEBUG:root:Multiprocessing Server Started: 127.0.0.1:31337
DEBUG:root:Total jobs in job queue: 3
DEBUG:root:Client connected to 127.0.0.1:31337
DEBUG:root:Created process 0
DEBUG:root:Created process 1
DEBUG:root:Created process 2
DEBUG:root:Created process 3
DEBUG:root:Created process 4
DEBUG:root:Created process 5
DEBUG:root:Created process 6
DEBUG:root:Created process 7
DEBUG:root:Created process 8
DEBUG:root:Created process 9
DEBUG:root:Created process 10
DEBUG:root:Created process 11
DEBUG:root:Created process 12
DEBUG:root:Created process 13
DEBUG:root:Created process 14
DEBUG:root:Created process 15
DEBUG:root:Created process 16
DEBUG:root:Created process 17
DEBUG:root:Created process 18
DEBUG:root:Created process 19
DEBUG:root:<Process(Process-2, started)>: STARTING UP!
DEBUG:root:<Process(Process-3, started)>: STARTING UP!
DEBUG:root:<Process(Process-4, started)>: STARTING UP!
DEBUG:root:<Process(Process-5, started)>: STARTING UP!
DEBUG:root:<Process(Process-6, started)>: STARTING UP!
DEBUG:root:<Process(Process-7, started)>: STARTING UP!
DEBUG:root:<Process(Process-2, started)>: I have a job!!!
DEBUG:root:<Process(Process-8, started)>: STARTING UP!
DEBUG:root:<Process(Process-9, started)>: STARTING UP!
DEBUG:root:<Process(Process-3, started)>: I have a job!!!
DEBUG:root:<Process(Process-5, started)>: No work! Returning.
DEBUG:root:<Process(Process-4, started)>: I have a job!!!
DEBUG:root:<Process(Process-6, started)>: No work! Returning.
DEBUG:root:<Process(Process-10, started)>: STARTING UP!
DEBUG:root:<Process(Process-11, started)>: STARTING UP!
DEBUG:root:<Process(Process-7, started)>: No work! Returning.
DEBUG:root:<Process(Process-12, started)>: STARTING UP!
DEBUG:root:<Process(Process-13, started)>: STARTING UP!
DEBUG:root:<Process(Process-8, started)>: No work! Returning.
DEBUG:root:<Process(Process-14, started)>: STARTING UP!
DEBUG:root:<Process(Process-9, started)>: No work! Returning.
DEBUG:root:<Process(Process-15, started)>: STARTING UP!
DEBUG:root:<Process(Process-16, started)>: STARTING UP!
DEBUG:root:<Process(Process-17, started)>: STARTING UP!
DEBUG:root:<Process(Process-18, started)>: STARTING UP!
DEBUG:root:<Process(Process-19, started)>: STARTING UP!
DEBUG:root:<Process(Process-10, started)>: No work! Returning.
DEBUG:root:<Process(Process-11, started)>: No work! Returning.
DEBUG:root:<Process(Process-20, started)>: STARTING UP!
DEBUG:root:<Process(Process-21, started)>: STARTING UP!
DEBUG:root:<Process(Process-12, started)>: No work! Returning.
DEBUG:root:<Process(Process-13, started)>: No work! Returning.
DEBUG:root:<Process(Process-14, started)>: No work! Returning.
DEBUG:root:<Process(Process-15, started)>: No work! Returning.
DEBUG:root:<Process(Process-16, started)>: No work! Returning.
DEBUG:root:<Process(Process-18, started)>: No work! Returning.
DEBUG:root:<Process(Process-19, started)>: No work! Returning.
DEBUG:root:<Process(Process-17, started)>: No work! Returning.
DEBUG:root:<Process(Process-20, started)>: No work! Returning.
DEBUG:root:<Process(Process-21, started)>: No work! Returning.
DEBUG:root:<Process(Process-2, started)>: Added results to the result_queue
DEBUG:root:<Process(Process-2, started)>: No work! Returning.
DEBUG:root:<Process(Process-3, started)>: Added results to the result_queue
DEBUG:root:<Process(Process-3, started)>: No work! Returning.
DEBUG:root:<Process(Process-4, started)>: Added results to the result_queue
DEBUG:root:<Process(Process-4, started)>: No work! Returning.
DEBUG:root:Items in job queue: 0
DEBUG:root:Items in result queue: 3
DEBUG:root:Beginning to combine the results queue
DEBUG:root:I have combined the results queue!
the 21399
of 12617
and 11869
to 10086
a 9269
in 7354
he 5676
i 5605
his 4685
it 4683
]0;fxfitz@ares: ~/multiprocess-wordcounter[01;32mfxfitz@ares[00m:[01;34m~/multiprocess-wordcounter[00m$ exit
exit

Script done on Sun Jun 28 23:56:59 2015
